In [48]:
import os
import sys
import pandas as pd

In [49]:
df= pd.read_csv("../data/metrics.csv").sort_values("created_at").dropna(axis=1, how="all",)

In [50]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1164430 entries, 307539 to 1164429
Data columns (total 9 columns):
 #   Column                     Non-Null Count    Dtype
---  ------                     --------------    -----
 0   id                         1164430 non-null  int64
 1   status                     1164430 non-null  object
 2   created_at                 1164430 non-null  object
 3   machineId                  1164430 non-null  int64
 4   connected_operators        1164430 non-null  object
 5   varnishLevelsTargetvolume  1164430 non-null  float64
 6   varnishLevelsTotalvolume   1164430 non-null  int64
 7   modules                    1164430 non-null  object
 8   events                     1164430 non-null  object
dtypes: float64(1), int64(3), object(5)
memory usage: 88.8+ MB

In [51]:
df.head()

,id,status,created_at,machineId,connected_operators,varnishLevelsTargetvolume,varnishLevelsTotalvolume,modules,events
307539,4169748,WARNING,2022-04-15 05:55:06.678000,14,"[{""name"": ""Viktor"", ""level"": ""Operator""}]",36192.322612,100000,"[{""sn"": """", ""name"": ""Print Engine 1"", ""type"": ...",[]
307540,4169749,WARNING,2022-04-15 05:55:06.829000,14,"[{""name"": ""Viktor"", ""level"": ""Operator""}]",36192.322612,100000,"[{""sn"": """", ""name"": ""Print Engine 1"", ""type"": ...","[{""source"": ""PLC"", ""message"": "" JV-Ti non prêt..."
307537,4169753,WARNING,2022-04-15 05:55:14.494000,14,"[{""name"": ""Viktor"", ""level"": ""Operator""}]",36192.322612,100000,"[{""sn"": """", ""name"": ""Print Engine 1"", ""type"": ...",[]
307541,4169758,WARNING,2022-04-15 05:55:24.503000,14,"[{""name"": ""Viktor"", ""level"": ""Operator""}]",36192.322612,100000,"[{""sn"": """", ""name"": ""Print Engine 1"", ""type"": ...",[]
307542,4169763,WARNING,2022-04-15 05:55:34.515000,14,"[{""name"": ""Viktor"", ""level"": ""Operator""}]",36192.322612,100000,"[{""sn"": """", ""name"": ""Print Engine 1"", ""type"": ...",[]

In [52]:
df=df[df.events != "[]"]

In [53]:
df.head()

,id,status,created_at,machineId,connected_operators,varnishLevelsTargetvolume,varnishLevelsTotalvolume,modules,events
307540,4169749,WARNING,2022-04-15 05:55:06.829000,14,"[{""name"": ""Viktor"", ""level"": ""Operator""}]",36192.322612,100000,"[{""sn"": """", ""name"": ""Print Engine 1"", ""type"": ...","[{""source"": ""PLC"", ""message"": "" JV-Ti non prêt..."
307613,4170152,IDLE,2022-04-15 06:06:35.404000,14,"[{""name"": ""Viktor"", ""level"": ""Operator""}]",36192.322612,100000,"[{""sn"": """", ""name"": ""Print Engine 1"", ""type"": ...","[{""source"": ""iFoil"", ""message"": "" JV-Ti non pr..."
307614,4170167,IDLE,2022-04-15 06:07:05.443000,14,"[{""name"": ""Viktor"", ""level"": ""Operator""}]",36192.322612,100000,"[{""sn"": """", ""name"": ""Print Engine 1"", ""type"": ...","[{""source"": ""PLC"", ""message"": "" Disponible"", ""..."
307612,4170172,IDLE,2022-04-15 06:07:15.471000,14,"[{""name"": ""Viktor"", ""level"": ""Operator""}]",36192.322612,100000,"[{""sn"": """", ""name"": ""Print Engine 1"", ""type"": ...","[{""source"": ""PLC"", ""message"": "" Chargeur: mode..."
307620,4170207,IDLE,2022-04-15 06:08:25.616000,14,"[{""name"": ""Viktor"", ""level"": ""Operator""}]",36192.322612,100000,"[{""sn"": """", ""name"": ""Print Engine 1"", ""type"": ...","[{""source"": ""PLC"", ""message"": "" Préchauffage"",..."

In [54]:
df.to_csv("../data/metrics_events.csv")